### ISSUE TITLE
Password on digicom registration for joomla users.

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#141]
If i am a registerd user in joomla already and want to buy something in digicom, i need to set my password again while registration, this is not really comfortable.

**Comment by codexpert** [comment]
You can login and buy product or in checkout process you can login and proceed. I'm not sure what you are referring. Attaching screenshot might help.

**Comment by shamsbd71** [comment]
@webnut-de 
can you please check it back. because when you purchase something and try to checkout it should give you 2 options
1. login
2. register
and after login it will complete the procedure to purchase and confirm cart

based on settings it may ask you to give billing info, but its not always

thanks

**Comment by webnut-de** [comment]
I will try to explain it.

I am already registerd as a user in my joomla. Now i want to buy something and digicom leads me to the regsitration form. Thats ok, because digicom needs more information.

What i mean is that i need to confirm my password again, though im already logged in. I hope its clear now.
