### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by shamsbd71** [themexpert/digicom#352]
@Gee Heijneman has submitted few isssue:

English Mistakes:
- [x] Issue 1 : Language
  When clicking the pay with paypal button:
  NOTICE  we are redirecting youR to Paypal   (should be redirecting you to Paypal) 
- [x] Issue 2 : Language
  Confirmation emails:
  This is an email to let you inform about your order#[ORDER_ID](should be  ’to let you know about your order’  OR  ‘to inform you about your order’)
- [x] Issue 3 : bug
  Anomalies / errors:
  Admin is not receiving an email when a new sale is made even though I have this option set to ‘yes’
- [x] Issue 4 : bug/config
  When buying in digicom and creating a login/profile there is an error message popping up:
  Notice
  You must provide at least one recipient email address.
  Even though the email address was filled out correctly and actually accepted and all works fine.
- [x] Issue 4 : registration/validation
  ANOMALY: 
  When buying a product in Digicom and creating a profile as part of the process the following happens:
  First I get an email from Joomla about my registration and with an activation link:
  Hello john lennon,

Thank you for registering at The Localising Food Project. Your account is created and must be activated before you can use it.
To activate the account select the following link or copy-paste it in your browser:
http://site.com/index.php/component/users/?task=registration.activate&token=*** 

After activation you may login to http://site.com/ using the following username and password:

Username: username
Password: pass

If I click this link It does nothing, it does not work and the user John Lennon stays ‘not activated’ in the backend of Joomla users.
If I then login and go to the ‘my downloads’ page, I can login correctly but get an notice:
Warning
Registration failed: Verification code not found.

**Comment by ledlightcircus** [comment]
This is an email to let you inform about your order  should be: This is an email to inform you about your order  etc   ☺

**Comment by shamsbd71** [comment]
@ledlightcircus can you explain issue 3? i have checked and its working fine. BTW for free order there is no new-order email, only complete email. or you can help me to understand the issue.

thanks

**Comment by ledlightcircus** [comment]
Hi,

If I make a test order, there is no email send to the admin of the site.
I have the option send email to admin¹ set to yes in Digicom
I also have my superuser account set to receive system emails.

Is that clear ?   Its not very important  but it would be nice if it works..

Thanks, Gee

**Comment by shamsbd71** [comment]
@ledlightcircus Can you join me in my private chat? i'm working on digicom these days and cant reproduce the erros :(
issue 3,4 need to produce :)

need your help to resolve them. i'm checking the last one. please join me in gitter chat
https://gitter.im/themexpert/digicom
thanks

**Comment by shamsbd71** [comment]
your email activation issue fixed

**Comment by ledlightcircus** [comment]
Hi Abu,

Thanks for that , ( workaround I had was to not have any email addresses
filled out, then it was sending to admin OK somehow.)

I am having a BIG problem now, I have added a few products (documentaries)
to our shop and now the My Downloads page stays totally blank !
It could have to do with deleting a product ( I deleted a test product ) I
noticed earlier that when I unpublished a product the My Download page was
blank too..
Don¹t know what to do, this is a live site and we expect lots of people
coming to the site to view the new trailers and possibly buy the documentary
!
But its not working now..

Aaaahhrch  please help

Localisingfood.com   logon: abu    pass:  aBu8204HtY
FTP   abu@earthcare-education.org    for FTP same pass


Thanks Much !

Gee

**Comment by ledlightcircus** [comment]
Hi Abu,

Sorry Disregard previous email,  I found the problem , was my own mistake of
course ☺
It would be really good though if the download page was not totally blank
when a product is not found...  Some kind of error message..

Thanks again !!!  ☺


Thanks for that , ( workaround I had was to not have any email addresses
filled out, then it was sending to admin OK somehow.)

I am having a BIG problem now, I have added a few products (documentaries)
to our shop and now the My Downloads page stays totally blank !
It could have to do with deleting a product ( I deleted a test product ) I
noticed earlier that when I unpublished a product the My Download page was
blank too..
Don’t know what to do, this is a live site and we expect lots of people
coming to the site to view the new trailers and possibly buy the documentary
!
But its not working now..

Aaaahhrch  please help

Thanks Much !

Gee

**Comment by shamsbd71** [comment]
hi, poke me in gitter chat @ledlightcircus 

https://gitter.im/themexpert/digicom

**Comment by ledlightcircus** [comment]
Hi Abu,

Hope you are well !
Hey I updated today from 1.3.2.2 to 1.3.9
Everything works only the downloads of the documentaries (our products) no
longer work !
This is what happens if I click the option to view the documentary in the
browser See image:


And this happens if I click the option to download the documentary to disk:


This was all working perfectly before !!!
Somehow the products don¹t correctly link to the video files any longer...
In the digicom products section a typical link to the video files at Vimeo
looks like this:
https://player.vimeo.com/external/186208553.hd.mp4?s=0e165e102028fb48270ca00
20f0c1ec2c126d17c&profile_id=119&download=1

Any help greatly appreciated !  We have a broken shop now.
If I don¹t hear from you soon I might have to run a backup restore...

Best, Sungee

**Comment by shamsbd71** [comment]
I have messaged you in gitter, please check there so we can fix it fast.
thanks

**Comment by michalip** [comment]
Hi Abu
In the release notes of the latest patch, it's said that there is an on/off option to show images in the details. But I cant find it anywhere. In which screen is this ?

**Comment by ledlightcircus** [comment]
Hi Abu,
I have send you logon info for the site, did you receive it ?
also I have a test user logon for you for the front-end so you can see what happens if a user/customer want to download a documentary that they have bought.
I will send it in private chat.
Thanks !

**Comment by ledlightcircus** [comment]
Hi Abu,

http://www.localisingfood.com/administrator
Login info:
name:   abu  passw:  aBu8204HtY

FTP:  earthcare-education.org
(localisingfood directory)
login:
abu@earthcare-education.org   for FTP same passw


Thanks so much !!!

Hi Abu,

Hope you are well !
Hey I updated today from 1.3.2.2 to 1.3.9
Everything works only the downloads of the documentaries (our products) no
longer work !
This is what happens if I click the option to view the documentary in the
browser See image:


And this happens if I click the option to download the documentary to disk:


This was all working perfectly before !!!
Somehow the products don¹t correctly link to the video files any longer...
In the digicom products section a typical link to the video files at Vimeo
looks like this:
https://player.vimeo.com/external/186208553.hd.mp4?s=0e165e102028fb48270ca00
20f0c1ec2c126d17c&profile_id=119&download=1

Any help greatly appreciated !  We have a broken shop now.
If I don¹t hear from you soon I might have to run a backup restore...

Best, Sungee

**Comment by shamsbd71** [comment]
Issue fixed, it was configuration issue for external files. thanks

**Comment by sifur** [comment]
How did you fix issue #4 (Account Activation) please?
I'm using latest version but I have registration page override from an older version.

Is it fixed on latest release or do I need any other configuration.

Thanks for your help.

**Comment by ledlightcircus** [comment]
Hi Abu,

Hope you are well !

Hey I have some anomalies with the Digicom Software;

* the Search function does not find anything in our DVD Shop / anything that
is Digicom it seems, it does not find our products.
* we have 3 categories for our Documentaries (home use ­ community screening
license ­ educational screening license) and if I have a customer that
bought for instance our Super Bundle for Community Screening License, in
their downloads page it says Documentaries Home Use¹ (instead of
Documentaries Community Screening License) but the products are correct. Any
idea why or how I can fix this ?

I have added you as a user to the site and you have the product Super
Bundle of All Current Docos ! Community Screening License¹
But as you can see in your downloads page it says Documentaries - License
for Home Use¹
Instead of Documentaries Community Screening License¹


Site; http://www.localisingfood.com
Logon: abu
pass: aBu8204HtY

Hope you can help..

Thanks very much !  Sungee

**Comment by shamsbd71** [comment]
Hi @ledlightcircus,
Please remove your sites access information from your comment! or update the settings now, its not safe to share information publicly. 

For the search, please enable search plugin, smart search plugin. we have removed default search plugin. if you want that you can request to make it custom. 

for downloads page, I didn't get it correctly. can you post it to our forum with more details?

thanks

**Comment by ledlightcircus** [comment]
Hi, plugins are enabled, I have re- indexed and tried everything but its not getting indexed..
Also do you guys have any idea when the 'short codes not working problem' is getting fixed ? otherwise I will go ahead and remove it from all my pages... eg the: {digicom id=1} short code.
Thanks ! ☺
